### ISSUE TITLE
Usage with custom dataset

### ISSUE THREAD

**Issue by rbhatia46** [FGiuliari/Trajectory-Transformer#13]
Hi,
Thanks for the amazing work, one of the best papers and repos I could find on this topic. I want to use this code with my custom dataset, which is very similar to Geolife, i.e. it has userID, timestamp, latitude(in degrees) and longitude(in degrees), and want to forecast the trajectories for future. Any guidance on how can I achieve this?

**Comment by FGiuliari** [comment]
Hi,
you would have to modify the dataloader to take into account the changes to the dataset.

practically you would have to modify row 47 to 52 in the baselineutils.py

   ```
raw_data = pd.read_csv(os.path.join(full_dt_folder, dt), delimiter=delim,
                                            names=["frame", "ped", "x", "y"],usecols=[0,1,2,3],na_values="?")

raw_data.sort_values(by=['frame','ped'], inplace=True)

inp,out,info=get_strided_data_clust(raw_data,gt,horizon,1)
```

As first try to see I would do some preprocessing on the data
1)pick a coordinate as a reference point and zero all the other values wrt to the reference point, and try to map the point in x,y coordinates.
2)Also I would make sure that the timestamps sampled at a regular interval. If they aren't your best bet would be to try and do some interpolation in order to get data taken at regular timestamp.

Once you do that you should be able to try just changing the column names in row 47.
