### ISSUE TITLE
Hello, I have a question

### ISSUE THREAD

**Issue by Eternal-rxk** [FGiuliari/Trajectory-Transformer#16]
Can you tell me the difference between Individual Transformer and QuantizedTF

**Comment by FGiuliari** [comment]
Sry for the late response.
IndividualTF is the standard regressive model.
Individual TF take as input a sequence of real values and output sequence of real values that represent the difference in positions between adjacent timesteps, it can only output a single possible future.

QuantizedTF is a version where we treat the problem as a classification problem (think of it as sentence generation in NLP, where the next word can be one of multiple plausible words).
We first cluster the speed vectors in the training set, then when we do the prediction instead of working directly with the differences like in the IndividualTF we input the cluster ids, and output the probability of the next movement to be in a given cluster. The prediction will be less accurate due to the model only be able to predictt the cluster centroids, but it now allow to output multiple predictions.
