### ISSUE TITLE
Implement --resume_train

### ISSUE THREAD

**Issue by themousepotato** [FGiuliari/Trajectory-Transformer#9]
`--resume_train` flag is in the args without any code being written for it. Model state dict is being saved for every epoch with the optimizer state dict missing which makes it impossible to restore training. The size of the files generated is enormous. I trained for houses dataset and by 204 epochs, ~ 40 GB was the size of the output files.

**Comment by FindTheAnswer** [comment]
Hi, have you solved the problem?

**Comment by FindTheAnswer** [comment]
> `--resume_train` flag is in the args without any code being written for it. Model state dict is being saved for every epoch with the optimizer state dict missing which makes it impossible to restore training. The size of the files generated is enormous. I trained for houses dataset and by 204 epochs, ~ 40 GB was the size of the output files.

Hi, have you solved the problem?

**Comment by FGiuliari** [comment]
I do not have much time to maintain the repo, but it should be fairly trivial to implement the resuming of the training on your own. In the training cycle, instead of saving a new file you just replace the old one (remember to save a copy of the most recent one in case something goes wrong during the saving of the new .pth). 

To save the optimizer parameters you can just save somewhere the internal variable _steps of the optimizer class.

**Comment by b-safwat** [comment]
After this code: 
```
import individual_TF
model = individual_TF.IndividualTF(2, 3, 3, N=args.layers,
                                       d_model=args.emb_size, d_ff=2048, h=args.heads, dropout=args.dropout,
                                       mean=[0, 0], std=[0, 0]).to(device)
```
add this:

```
if args.resume_train:
        model.load_state_dict(torch.load(f'models/Individual/{args.name}/model.pth'))

```
